### ISSUE TITLE
NRF52 support

### ISSUE THREAD

**Issue by zachtos** [sparkfun/SparkFun_LSM6DS3_Arduino_Library#10]
Please add support for sparkfun NRF52840 module, so I can use this sparkfun library.

**Comment by edspark** [comment]
I [updated the library](https://github.com/sparkfun/SparkFun_LSM6DS3_Arduino_Library/commit/a440c1dce71415d03b3babd0c77441ffef160cdd) so that it didn't yell about using deprecated SPI functions and tested on the [nrf52840 MicroMod Processor](https://www.sparkfun.com/products/16984) using I2C and it works.
