### ISSUE TITLE
LSM6DSR

### ISSUE THREAD

**Issue by TinManAkshay** [sparkfun/SparkFun_LSM6DS3_Arduino_Library#18]
Hi,

Can these libraries be used for LSM6DSR module?

Thanks,
Akshay

**Comment by edspark** [comment]
I compared the registers between the LSM6DSR and this product and no luck. However I compared the LSM6DSR and our other product, the [LSM6DSO](https://github.com/sparkfun/SparkFun_Qwiic_6DoF_LSM6DSO_Arduino_Library) and they are compatible in their core functionality. The LSM6DSR has a few EXTRA registers that are not used in the LSM6DSO, but otherwise all register addresses and functions line up.
