### ISSUE TITLE
average of last second

### ISSUE THREAD

**Issue by priema** [sparkfun/SparkFun_LSM6DS3_Arduino_Library#4]
is there a possibility to get the average values of the last second?

**Comment by zencuke** [comment]
The traditional method is to read the values in the application and average the result. That is simple in the application but would be complicated to add to the library.

**Comment by edspark** [comment]
@zencuke is correct. It's much easier and more transparent as to what is happening if you were to do this in your code, rather than being buried in the Arduino Library folder. Look at using the [millis](https://www.arduino.cc/reference/en/language/functions/time/millis/), then divide the values by the number of samples gathered over the past second.
